Update to NuGet 2.8.3
Fixes error when installing xunit.core 2.0.0-rc1-build2826:

System.InvalidOperationException: 'xunit.core' already has a
dependency defined for 'xunit.extensibility.core'.