Check project item type before adding TypeScript file to context.
Ignore all project item types apart from None and TypeScriptCompile.
This fixes the startup exception when opening SharpDevelop.Tests.sln
with SharpDevelop when the TypeScript addin is enabled.

System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at ICSharpCode.TypeScriptBinding.Hosting.TypeScriptContextProvider.AddFileToProjectContext(TypeScriptContext context, FileName fileName)
   at ICSharpCode.TypeScriptBinding.Hosting.TypeScriptContextProvider.CreateProjectContext(TypeScriptProject project)
   at ICSharpCode.TypeScriptBinding.TypeScriptProjectMonitor.CreateTypeScriptContextIfProjectHasTypeScriptFiles(IProject project)
   at ICSharpCode.TypeScriptBinding.TypeScriptProjectMonitor.SolutionLoaded(Object sender, SolutionEventArgs e)